[package]
name = "proyecto_diorama"
version = "0.1.0"
edition = "2024"

[dependencies]
minifb = "0.24"
image = "0.24"
rand = "0.8"
rayon = "1.8"
winit = "0.30.12"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
